version: '3.8'

services:
  # PostgreSQL Database with PostGIS
  database:
    image: postgis/postgis:15-3.4
    container_name: pipeline_risk_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pipeline_risk_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pipeline_risk_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
